### ISSUE TITLE
[wishlist] Drop the unsafe ensure_buffer_len()

### ISSUE THREAD

**Issue by Shnatsel** [ruuda/claxon#13]
It would be nice to refactor `ensure_buffer_len()` into safe code so that bugs such as #10 are statically ruled out by the compiler, without sacrificing performance.

This is interesting from the API design and best practices perspective. Writing data into a preallocated buffer is a very common thing to do in systems programming, so the compiler and stdlib should support a safe and idiomatic way to do it. This may be a good case study for unsafe code guidelines WG and/or the emerging security working group.

Some ideas to get the ball rolling:

 1. Use buffer initialization such as `vec![0, len]` that the stdlib optimizes into as cheap memory zeroing as possible. Sadly this is still going to involve some overhead, unless we convince the optimizer that the entire buffer is always overwritten.
1. Instead of setting the buffer length in advance, preallocate a vector and use the [Write](https://doc.rust-lang.org/std/io/trait.Write.html) trait or [extend_from_slice()](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extend_from_slice) to safely write into it without zeroing memory.

**Comment by Shnatsel** [comment]
Is there a particular reason why you went with slicing the buffer and passing the slices to decoding functions instead of passing the buffer to decoding functions and using `buffer.extend()` or similar? [Extend trait for reference](https://doc.rust-lang.org/std/iter/trait.Extend.html)

**Comment by ruuda** [comment]
Closed by https://github.com/ruuda/claxon/commit/fec24678c7086aa4b2528bd7542f31d978b81b90.
