### ISSUE TITLE
Support reading flac tag

### ISSUE THREAD

**Issue by gbip** [ruuda/claxon#2]
Hello,
Is it possible to decode "flac tag" (or vorbis comments) with your library ?
It seems that it is exposed in the library through MetadataBlock, but I am not sure.
Thanks !

**Comment by ruuda** [comment]
Claxon currently does not support reading Vorbis comments. The reason for this is simply [that it has not been implemented yet](https://github.com/ruuda/claxon/blob/b7c6440e408f640e65222d463c4df542031d89a0/src/metadata.rs#L141-L145). I do intend to implement this when I find the time. If you like to have a go at implementing this yourself, I could give you a few pointers. It is not hard, just a bit tedious.

In the mean time, you could take a look at the [metaflac](https://crates.io/crates/metaflac) crate to read Vorbis comments.

**Comment by ruuda** [comment]
I am pleased to announce that as of cf09824eee874ec218f10c2cf6ea7ad69888b534, Claxon can now read Vorbis comments!

Take a look at the `FlacReader::tags()` iterator and `FlacReader::get_tag()`. I also added [a small example](https://github.com/ruuda/claxon/blob/f1d637d4fa3a38f6681535e3dc8c1999d9958e6d/examples/tags.rs).
