### ISSUE TITLE
Last call on FLAC specification

### ISSUE THREAD

**Issue by ktmf01** [ruuda/claxon#33]
Sorry for bothering you all this way, I really hope you don't mind.

To implement FLAC decoding in Claxon, you might have used [the FLAC format specification](https://xiph.org/flac/format.html) on the FLAC website. If so, you probably needed to dive into some actual code (libFLAC or ffmpeg) to understand the finer points. An IETF working group has tried to improve this document, trying to include those finer points. In fact, I know @ruuda contributed to this a few years ago. However, all but a few lines have changed since and it is on the verge of being turned in for final checks and publication as an RFC. A so-called working group last call has been issued, which lasts 2 weeks.

As you've had first-hand experience implementing FLAC from scratch, you probably know best what implementation details needed extra attention. It would be very valuable to have your feedback on the FLAC format for this document.

I hope you can provide some insights.

The latest draft can be found here https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/

**Comment by ruuda** [comment]
Hi @ktmf01, thanks for reaching out. I follow flac-dev and I had seen the last call. I scrolled through the RFC a bit, but I did not read it in detail. I will try to take a closer look, but I’m not sure I will manage to find the time before the deadline.

**Comment by ruuda** [comment]
I sent an email with a few small remarks to draft-ietf-cellar-flac@ietf.org. Overall the new spec looks clear and well-written!
