### ISSUE TITLE
Frame CRC mismatch

### ISSUE THREAD

**Issue by pkkolos** [ruuda/claxon#4]
I have a FLAC file with this frame: `FF F8 C9 18 E0 B2 95 8E 01 80 01 00 00 03 28 92` followed by this frame: `FF F8 C9 18 E0 B2 96 87 01 80 01 00 00 03 11 08`.

Using flac --analyze I get the following for this 2 frames:
```
frame=3221	offset=26178049	bits=128	blocksize=4096	sample_rate=44100	channels=2	channel_assignment=INDEPENDENT
	subframe=0	wasted_bits=1	type=CONSTANT	value=1
	subframe=1	wasted_bits=0	type=CONSTANT	value=3
frame=3222	offset=26178065	bits=128	blocksize=4096	sample_rate=44100	channels=2	channel_assignment=INDEPENDENT
	subframe=0	wasted_bits=1	type=CONSTANT	value=1
	subframe=1	wasted_bits=0	type=CONSTANT	value=3
```

But with claxon I get the following:
```
Frame Number: FrameNumber(3221)
Block Size: 4096
Sample Rate: Some(44100)
Channel Assignment: Independent(2)
Bits per Sample: Some(16)
CRC8: 8e (Expected: 8e)

Subframe Type: Constant
Wasted Bits: 1
Constant Value: 2

Subframe Type: Constant
Wasted Bits: 0
Constant Value: 6

CRC16: 9200 (Expected: 92ff)
```

As you can see it parses wrong the two subframes, reading past the frame (it reads the value `92 FF` for the frame CRC instead of `28 92` as it should).

Checking the reference implementation I found that the wasted bits are subtracted from the frames' bits per sample ([source][1]), something that claxon doesn't do and that's why it reads more bits than it should, resulting in frame CRC mismatch.

Adding this snippet
```
    let mut bps = bps;
    if header.wasted_bits_per_sample > 0 {
        bps -= header.wasted_bits_per_sample;
    }
```
[here][2], the file is decoded fine, although there should be a check that the wasted bits are not more than the bits per sample.

[1]: https://git.xiph.org/?p=flac.git;a=blob;f=src/libFLAC/stream_decoder.c;h=a5527511d195f9428c817ad6dbe57e8af03a2f1b;hb=HEAD#l2480
[2]: https://github.com/ruuda/claxon/blob/master/src/subframe.rs#L197

**Comment by ruuda** [comment]
Thanks for the elaborate report. I found a file in my personal library that failed to decode, and your proposed fix makes it decode properly. I’ve pushed the fix to master.

I am also verifying my entire library against the reference decoder now.

**Comment by pkkolos** [comment]
Thanks for the quick response.
